source ~/.zsh/aliases.zsh 2>/dev/null
source ~/.zsh/bindkey.zsh 2>/dev/null
source ~/.zsh/completion.zsh 2>/dev/null
source ~/.zsh/exports.zsh 2>/dev/null
source ~/.zsh/functions.zsh 2>/dev/null
source ~/.zsh/history.zsh 2>/dev/null
source ~/.zsh/path.zsh 2>/dev/null
source ~/.zsh/plugins.zsh 2>/dev/null
source ~/.zsh/prompt.zsh 2>/dev/null
source ~/.zsh/setopt.zsh 2>/dev/null
source ~/.zsh/theming.zsh 2>/dev/null

# ZSH Plugins
source ~/.zsh/powerlevel10k/powerlevel10k.zsh-theme 2>/dev/null
source ~/.zsh/zsh-autosuggestions/zsh-autosuggestions.zsh 2>/dev/null
source ~/.zsh/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh 2>/dev/null
source /usr/share/autojump/autojump.zsh 2>/dev/null

# ZSH p10k Theme
POWERLEVEL9K_DISABLE_CONFIGURATION_WIZARD=true
[[ ! -f ~/.zsh/.p10k.zsh ]] || source ~/.zsh/.p10k.zsh 2>/dev/null

# Install Ruby Gems to ~/gems
export GEM_HOME="$HOME/gems"

export PATH="$HOME/.local/bin:$HOME/.local/share/gem/ruby/3.0.0/bin:$PATH"
