---
- name: System setup | OpenSSH | Install package
  ansible.builtin.package:
    name: "{{ openssh_package }}"
    state: latest
  notify: Restart sshd

- name: System setup | OpenSSH | Ensure we have our version of sshd_config file
  ansible.builtin.lineinfile:
    path: /etc/ssh/sshd_config
    regexp: "^# Modified by"
    state: absent
  check_mode: yes
  changed_when: false
  register: sshd_template

- name: System setup | OpenSSH | Generate sshd_config file from template
  ansible.builtin.template:
    src: sshd_config.j2
    dest: /etc/ssh/sshd_config
    owner: root
    group: root
    mode: 0644
  when: not sshd_template.found

- name: System setup | OpenSSH | Check for WSL
  ansible.builtin.command: systemd-detect-virt
  register: virt_env_output
  changed_when: false

- name: System setup | OpenSSH | Update port for WSL
  ansible.builtin.lineinfile:
    dest: /etc/ssh/sshd_config
    regexp: "Port 22"
    line: "Port 2222"
  failed_when: false
  when: virt_env_output.stdout == "wsl"

- name: System setup | OpenSSH | Enable daemon
  ansible.builtin.service:
    name: "{{ openssh_service }}"
    enabled: yes
    state: started
