---
- name: Converge
  hosts: all
  become: true
  pre_tasks:
    # - name: Update apt cache.
    #   apt: update_cache=true cache_valid_time=600
    #   when: ansible_os_family == "Debian"

    # - name: Install test dependencies (RedHat).
    #   package: name=which state=present
    #   when: ansible_os_family == "RedHat"

  roles:
    - role: jokerwrld999.bootstrap

  tasks:
    - name: Output Failed Task
      ansible.builtin.fail:
        msg: |-
          ⚠️  Ansible provision failed on *{{ ansible_hostname }}*\n\n
          *Task*:  {{ ansible_failed_task.name }}\n
          *Action*: {{ ansible_failed_task.action }}\n
          *Error Message*: \n ```{{ ansible_failed_result | to_nice_json }}```
      when:
        - task_failed is defined
        - task_failed == true
