---
- name: Users | {{ custom_user }} | Create user's group
  ansible.builtin.group:
    name: "{{ custom_user }}"
    state: present

- name: Users | {{ custom_user }} | Create user
  ansible.builtin.user:
    name: "{{ custom_user }}"
    group: "{{ custom_user }}"
    groups: "{{ sudo_group }}"
    append: true
    password: "{{ custom_user_passwd }}"
    update_password: on_create
    shell: /bin/zsh
    generate_ssh_key: yes
    ssh_key_type: "ed25519"
    ssh_key_file: .ssh/ed_25519
    ssh_key_comment: "$HOSTNAME"
    state: present

- name: Users | {{ custom_user }} | Stat sudoers file
  ansible.builtin.stat:
    path: "/etc/sudoers.d/sudoers_{{ custom_user }}"
  register: sudoers_file

- name: Users | {{ custom_user }} | Copy sudoers file
  ansible.builtin.copy:
    src: "users/sudoers_custom_user"
    dest: "/etc/sudoers.d/sudoers_{{ custom_user }}"
    owner: root
    group: root
    mode: 0440
  register: new_sudoers_file
  when: sudoers_file.stat.exists == false

- name: Users | {{ custom_user }} | Change sudoers file
  ansible.builtin.lineinfile:
    dest: "/etc/sudoers.d/sudoers_{{ custom_user }}"
    regexp: "^custom_user"
    line: "{{ custom_user }} ALL=(ALL) NOPASSWD: ALL"
  when: new_sudoers_file.changed

- name: Users | Custom user | Reconnect to server session
  ansible.builtin.meta: reset_connection

- name: Users | {{ custom_user }} | Stat dot_config folder
  ansible.builtin.stat:
    path: "/home/{{ custom_user }}/.config"
  register: config_dir

- name: Users | {{ custom_user }} | Create config directories
  ansible.builtin.file:
    path: "/home/{{ custom_user }}/{{ item.dir }}"
    state: directory
    owner: "{{ custom_user }}"
    group: "{{ custom_user }}"
    mode: 0700
  with_items:
    - { dir: ".config" }
  when: config_dir.stat.exists == false

- name: Users | {{ custom_user }} | Create config directories
  ansible.builtin.file:
    path: "/home/{{ custom_user }}/{{ item.dir }}"
    state: directory
    owner: "{{ custom_user }}"
    group: "{{ custom_user }}"
    mode: 0700
  with_items:
    - { dir: ".config/htop" }
    - { dir: "github" }
    - { dir: ".ssh" }
    - { dir: ".zsh" }

- name: Users | {{ custom_user }} | Create temp dir
  ansible.builtin.file:
    path: "/home/{{ custom_user }}/{{ item.dir }}"
    state: directory
    owner: "{{ custom_user }}"
    group: "{{ custom_user }}"
    mode: 0755
  with_items:
    - { dir: "{{ temp_dir }}" }

- name: Users | {{ custom_user }} | Copy dotfiles
  ansible.builtin.copy:
    src: "users/custom_user/{{ item.src }}"
    dest: "/home/{{ custom_user }}/{{ item.dest }}"
    owner: "{{ custom_user }}"
    group: "{{ custom_user }}"
    mode: 0600
  with_items:
    - { src: "htop/htoprc", dest: ".config/htop/htoprc" }
    - { src: "inputrc", dest: ".inputrc" }
    - { src: "zsh/zshrc", dest: ".zshrc" }
    - { src: "zsh/p10k.zsh", dest: ".zsh/.p10k.zsh" }

- name: Users | {{ custom_user }} | Clone zsh-autosuggestions plugin repository
  become_user: "{{ custom_user }}"
  ansible.builtin.git:
    repo: https://github.com/zsh-users/zsh-autosuggestions
    dest: "/home/{{ custom_user }}/.zsh/zsh-autosuggestions"
    force: yes

- name: Users | {{ custom_user }} | Clone zsh-syntax-highlighting plugin repository
  become_user: "{{ custom_user }}"
  ansible.builtin.git:
    repo: https://github.com/zsh-users/zsh-syntax-highlighting.git
    dest: "/home/{{ custom_user }}/.zsh/zsh-syntax-highlighting"
    force: yes

- name: Users | {{ custom_user }} | Clone powerlevel10k plugin repository
  become_user: "{{ custom_user }}"
  ansible.builtin.git:
    repo: https://github.com/romkatv/powerlevel10k.git
    dest: "/home/{{ custom_user }}/.zsh/powerlevel10k"
    force: yes

- name: Users | {{ custom_user }} | Copy zsh config files
  ansible.builtin.copy:
    src: "users/custom_user/zsh/{{ item.src }}"
    dest: "/home/{{ custom_user }}/.zsh/{{ item.src }}"
    owner: "{{ custom_user }}"
    group: "{{ custom_user }}"
    mode: 0600
  with_items:
    - { src: "aliases.zsh" }
    - { src: "bindkey.zsh" }
    - { src: "completion.zsh" }
    - { src: "exports.zsh" }
    - { src: "functions.zsh" }
    - { src: "history.zsh" }
    - { src: "path.zsh" }
    - { src: "plugins.zsh" }
    - { src: "prompt.zsh" }
    - { src: "setopt.zsh" }
    - { src: "theming.zsh" }
