---
- name: Software | Utilities | Install packages
  ansible.builtin.package:
    name:
      - at
      - cifs-utils
      - colordiff
      - "{{ cron_package }}"
      - "{{ dns_utils_package }}"
      - htop
      - jq
      - "{{ lm_sensors_package }}"
      - lsof
      - ncdu
      - neofetch
      - net-tools
      - "{{ nfs_client_package }}"
      - nmap
      - openssl
      - "{{ rename_package }}"
      - rsync
      - speedtest-cli
      - sshfs
      - terraform
      - tldr
      - traceroute
      - tree
      - unzip
      - "{{ webp }}"
      - wget
      - whois

- name: Software | Utilities | Exclude packages Rocky
  ansible.builtin.package:
    name:
      - "{{ aws_cli }}"
  when: ansible_distribution != "Rocky"

- name: Software | Utilities | Exclude packages Rocky 8
  ansible.builtin.package:
    name:
      - bat
  when: ansible_distribution != "Rocky" and ansible_distribution_major_version != "8"

- name: Software | Utilities | Install autojump
  ansible.builtin.package:
    name:
      - "{{ autojump_package }}"
  when: ansible_distribution != "Archlinux"

- name: Software | Utilities | Install packages Arch
  become_user: "{{ custom_user }}"
  kewlfft.aur.aur:
    use: yay
    name:
      - "{{ autojump_package }}"
      - kubectl
  when: ansible_distribution == "Archlinux"

- name: Software | Utilities | Install packages Rocky
  ansible.builtin.dnf:
    name:
      - "{{ aws_cli }}"
    skip_broken: true
  when: ansible_distribution == "Rocky"

- name: Software | Utilities | Install Helm
  ansible.builtin.shell: |
    curl https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | bash
  args:
    creates: /usr/local/bin/helm
  when: ansible_distribution != "Rocky"

- name: Software | Utilities | Install Kubernetes
  ansible.builtin.shell: |
    curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
    install -o root -g root -m 0755 kubectl /usr/local/bin/kubectl
    rm -f kubectl
  args:
    creates: /usr/local/bin/kubectl
  when: ansible_distribution in ["Debian", "Ubuntu"]
