---
# **** Distro-specific Tasks For Arch
# **** Installing AUR Helper Package
- name: Software | Tweaks | Clone yay Arch
  become_user: "{{ custom_user }}"
  ansible.builtin.git:
    repo: https://aur.archlinux.org/yay-bin.git
    dest: "~/{{ temp_dir }}/yay"
    update: true
  when: ansible_distribution == "Archlinux"

- name: Software | Tweaks | Install yay Arch
  become_user: "{{ custom_user }}"
  ansible.builtin.command:
    chdir: "~/{{ temp_dir }}/yay"
    cmd: "makepkg -sfi --noconfirm"
    creates: /usr/bin/yay
  when: ansible_distribution == "Archlinux"
